{% set name = "types-dateparser" %}
{% set version = "1.1.4.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-dateparser-{{ version }}.tar.gz
  sha256: f9f147147a897ecb99491f59772ab1be1b7a0842fbc22e85ca37c6995b563b52

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/dateparser-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for dateparser
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
